2021-07-26 03:38:55,396 [INFO] root consoleworker.py:434	Log file created
2021-07-26 03:38:55,396 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7fb76bcadc10> added
2021-07-26 03:38:55,396 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fb76bcf5850> added
2021-07-26 03:38:55,397 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fb76bc99a50> added
2021-07-26 03:38:55,397 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-07-26_03-38-55.276179
2021-07-26 03:38:55,397 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-07-26 03:38:55,411 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-07-26 03:38:55,411 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-07-26 03:38:55,412 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-07-26 03:38:55,412 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-07-26 03:38:55,415 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2021-07-26 03:38:55,415 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-07-26 03:38:55,416 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-07-26 03:38:55,416 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-07-26 03:38:55,416 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-07-26 03:38:55,416 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fb76b9f0290>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7fb76b966650>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7fb76b966150>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7fb76b966710>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7fb76b966790>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7fb76b9f0110>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x7fb76b9f0bd0>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7fb76bd15a10>}
2021-07-26 03:38:55,416 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fb76b9f0290>
2021-07-26 03:38:55,417 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-07-26 03:38:55,421 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-38-55.276179/answ_aEWGx0.log
2021-07-26 03:38:55,423 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-38-55.276179/phout_qA4_Gz.log
2021-07-26 03:38:55,423 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-38-55.276179/phantom_stat_dVMTA4.log
2021-07-26 03:38:55,426 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-38-55.276179/phantom_lNd82I.log
2021-07-26 03:38:55,426 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: host.docker.internal:8185
2021-07-26 03:38:55,427 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-07-26 03:38:55,430 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('192.168.65.2', 8185)), (2, 2, 17, '', ('192.168.65.2', 8185)), (2, 3, 0, '', ('192.168.65.2', 8185))]
2021-07-26 03:38:55,430 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.65.2 and port 8185
2021-07-26 03:38:57,485 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.65.2]:8185 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-07-26 03:38:57,486 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.65.2]:8185
2021-07-26 03:38:57,487 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.65.2]:8185
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.65.2]:8185, use phantom.connection_test=0 to disable it
2021-07-26 03:38:57,488 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.65.2 and port 8185
2021-07-26 03:38:59,530 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.65.2]:8185 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-07-26 03:38:59,531 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.65.2]:8185
2021-07-26 03:38:59,531 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.65.2]:8185
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.65.2]:8185, use phantom.connection_test=0 to disable it
2021-07-26 03:38:59,531 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.65.2 and port 8185
2021-07-26 03:39:01,576 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.65.2]:8185 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-07-26 03:39:01,577 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.65.2]:8185
2021-07-26 03:39:01,578 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.65.2]:8185
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.65.2]:8185, use phantom.connection_test=0 to disable it
2021-07-26 03:39:01,580 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-07-26 03:39:01,603 [INFO] root consoleworker.py:269	Trying to clean up
2021-07-26 03:39:01,604 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_oRxVu5.lock
2021-07-26 03:39:01,611 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-07-26 03:39:01,613 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-07-26 03:39:01,626 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-07-26 03:39:01,627 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-07-26_03-38-55.276179
2021-07-26 03:39:01,628 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-38-55.276179/answ_aEWGx0.log to /var/loadtest/logs/2021-07-26_03-38-55.276179/answ_aEWGx0.log
2021-07-26 03:39:01,632 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-38-55.276179/answ_aEWGx0.log
2021-07-26 03:39:01,632 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-07-26_03-38-55.276179/validation_error.yaml
2021-07-26 03:39:01,633 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-07-26 03:39:01,634 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-38-55.276179/phantom_lNd82I.log to /var/loadtest/logs/2021-07-26_03-38-55.276179/phantom_lNd82I.log
2021-07-26 03:39:01,637 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-38-55.276179/phantom_lNd82I.log
2021-07-26 03:39:01,637 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-38-55.276179/phantom_stat_dVMTA4.log to /var/loadtest/logs/2021-07-26_03-38-55.276179/phantom_stat_dVMTA4.log
2021-07-26 03:39:01,640 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-38-55.276179/phantom_stat_dVMTA4.log
2021-07-26 03:39:01,641 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-38-55.276179/phout_qA4_Gz.log to /var/loadtest/logs/2021-07-26_03-38-55.276179/phout_qA4_Gz.log
2021-07-26 03:39:01,643 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-38-55.276179/phout_qA4_Gz.log
