2021-07-26 03:56:37,630 [INFO] root consoleworker.py:434	Log file created
2021-07-26 03:56:37,631 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7fc73f983c10> added
2021-07-26 03:56:37,632 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fc73f9cb850> added
2021-07-26 03:56:37,632 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fc73f96fa50> added
2021-07-26 03:56:37,633 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-07-26_03-56-37.567637
2021-07-26 03:56:37,633 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-07-26 03:56:37,634 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-07-26 03:56:37,634 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-07-26 03:56:37,635 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-07-26 03:56:37,635 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-07-26 03:56:37,640 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2021-07-26 03:56:37,641 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-07-26 03:56:37,641 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-07-26 03:56:37,642 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-07-26 03:56:37,642 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-07-26 03:56:37,642 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fc73f6c6290>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7fc73f63c650>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7fc73f63c850>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7fc73f63c710>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7fc73f63c150>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7fc73f6c6110>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x7fc73f6c6bd0>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7fc73f9eba10>}
2021-07-26 03:56:37,643 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fc73f6c6290>
2021-07-26 03:56:37,643 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-07-26 03:56:37,652 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-56-37.567637/answ__zpJwV.log
2021-07-26 03:56:37,655 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-56-37.567637/phout_KpQOLm.log
2021-07-26 03:56:37,655 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-56-37.567637/phantom_stat_0mTc9u.log
2021-07-26 03:56:37,658 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-56-37.567637/phantom_6ReqoM.log
2021-07-26 03:56:37,658 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: host.docker.internal:8081
2021-07-26 03:56:37,660 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-07-26 03:56:37,662 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('192.168.65.2', 8081)), (2, 2, 17, '', ('192.168.65.2', 8081)), (2, 3, 0, '', ('192.168.65.2', 8081))]
2021-07-26 03:56:37,662 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.65.2 and port 8081
2021-07-26 03:56:39,710 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.65.2]:8081 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-07-26 03:56:39,711 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.65.2]:8081
2021-07-26 03:56:39,712 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.65.2]:8081
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.65.2]:8081, use phantom.connection_test=0 to disable it
2021-07-26 03:56:39,713 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.65.2 and port 8081
2021-07-26 03:56:41,747 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.65.2]:8081 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-07-26 03:56:41,747 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.65.2]:8081
2021-07-26 03:56:41,748 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.65.2]:8081
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.65.2]:8081, use phantom.connection_test=0 to disable it
2021-07-26 03:56:41,748 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.65.2 and port 8081
2021-07-26 03:56:43,802 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.65.2]:8081 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-07-26 03:56:43,803 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.65.2]:8081
2021-07-26 03:56:43,803 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.65.2]:8081
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.65.2]:8081, use phantom.connection_test=0 to disable it
2021-07-26 03:56:43,804 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-07-26 03:56:43,805 [INFO] root consoleworker.py:269	Trying to clean up
2021-07-26 03:56:43,805 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_iNlInN.lock
2021-07-26 03:56:43,807 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-07-26 03:56:43,808 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-07-26 03:56:43,812 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-07-26 03:56:43,813 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-07-26_03-56-37.567637
2021-07-26 03:56:43,813 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-56-37.567637/answ__zpJwV.log to /var/loadtest/logs/2021-07-26_03-56-37.567637/answ__zpJwV.log
2021-07-26 03:56:43,815 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-56-37.567637/answ__zpJwV.log
2021-07-26 03:56:43,816 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-56-37.567637/phantom_stat_0mTc9u.log to /var/loadtest/logs/2021-07-26_03-56-37.567637/phantom_stat_0mTc9u.log
2021-07-26 03:56:43,818 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-56-37.567637/phantom_stat_0mTc9u.log
2021-07-26 03:56:43,818 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-07-26_03-56-37.567637/validation_error.yaml
2021-07-26 03:56:43,818 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-07-26 03:56:43,819 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-56-37.567637/phout_KpQOLm.log to /var/loadtest/logs/2021-07-26_03-56-37.567637/phout_KpQOLm.log
2021-07-26 03:56:43,821 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-56-37.567637/phout_KpQOLm.log
2021-07-26 03:56:43,821 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-56-37.567637/phantom_6ReqoM.log to /var/loadtest/logs/2021-07-26_03-56-37.567637/phantom_6ReqoM.log
2021-07-26 03:56:43,823 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-56-37.567637/phantom_6ReqoM.log
