2021-07-26 03:40:51,562 [INFO] root consoleworker.py:434	Log file created
2021-07-26 03:40:51,563 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7f3b6816bc10> added
2021-07-26 03:40:51,563 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f3b681b3850> added
2021-07-26 03:40:51,563 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f3b68157a50> added
2021-07-26 03:40:51,563 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-07-26_03-40-51.489938
2021-07-26 03:40:51,564 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-07-26 03:40:51,564 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-07-26 03:40:51,565 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-07-26 03:40:51,565 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-07-26 03:40:51,565 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-07-26 03:40:51,569 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2021-07-26 03:40:51,569 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-07-26 03:40:51,570 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-07-26 03:40:51,570 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-07-26 03:40:51,570 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-07-26 03:40:51,570 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f3b67eae290>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7f3b67e24650>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7f3b67e24150>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7f3b67e24710>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7f3b67e24790>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7f3b67eae110>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x7f3b67eaebd0>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7f3b681d3a10>}
2021-07-26 03:40:51,571 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f3b67eae290>
2021-07-26 03:40:51,571 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-07-26 03:40:51,576 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-40-51.489938/answ_UYviMc.log
2021-07-26 03:40:51,578 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-40-51.489938/phout_oIRiKL.log
2021-07-26 03:40:51,578 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-40-51.489938/phantom_stat_Hk3hai.log
2021-07-26 03:40:51,580 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-26_03-40-51.489938/phantom_Y4w_mX.log
2021-07-26 03:40:51,581 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: host.docker.internal:8185
2021-07-26 03:40:51,582 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-07-26 03:40:51,584 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('192.168.65.2', 8185)), (2, 2, 17, '', ('192.168.65.2', 8185)), (2, 3, 0, '', ('192.168.65.2', 8185))]
2021-07-26 03:40:51,584 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.65.2 and port 8185
2021-07-26 03:40:53,628 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.65.2]:8185 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-07-26 03:40:53,628 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.65.2]:8185
2021-07-26 03:40:53,629 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.65.2]:8185
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.65.2]:8185, use phantom.connection_test=0 to disable it
2021-07-26 03:40:53,629 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.65.2 and port 8185
2021-07-26 03:40:55,674 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.65.2]:8185 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-07-26 03:40:55,674 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.65.2]:8185
2021-07-26 03:40:55,674 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.65.2]:8185
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.65.2]:8185, use phantom.connection_test=0 to disable it
2021-07-26 03:40:55,675 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.65.2 and port 8185
2021-07-26 03:40:57,719 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.65.2]:8185 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-07-26 03:40:57,720 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.65.2]:8185
2021-07-26 03:40:57,720 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.65.2]:8185
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.65.2]:8185, use phantom.connection_test=0 to disable it
2021-07-26 03:40:57,721 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-07-26 03:40:57,731 [INFO] root consoleworker.py:269	Trying to clean up
2021-07-26 03:40:57,731 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_UNBRQo.lock
2021-07-26 03:40:57,734 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-07-26 03:40:57,734 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-07-26 03:40:57,739 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-07-26 03:40:57,739 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-07-26_03-40-51.489938
2021-07-26 03:40:57,740 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-40-51.489938/answ_UYviMc.log to /var/loadtest/logs/2021-07-26_03-40-51.489938/answ_UYviMc.log
2021-07-26 03:40:57,742 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-40-51.489938/answ_UYviMc.log
2021-07-26 03:40:57,742 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-40-51.489938/phantom_stat_Hk3hai.log to /var/loadtest/logs/2021-07-26_03-40-51.489938/phantom_stat_Hk3hai.log
2021-07-26 03:40:57,744 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-40-51.489938/phantom_stat_Hk3hai.log
2021-07-26 03:40:57,744 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-07-26_03-40-51.489938/validation_error.yaml
2021-07-26 03:40:57,745 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-07-26 03:40:57,745 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-40-51.489938/phout_oIRiKL.log to /var/loadtest/logs/2021-07-26_03-40-51.489938/phout_oIRiKL.log
2021-07-26 03:40:57,746 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-40-51.489938/phout_oIRiKL.log
2021-07-26 03:40:57,747 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-26_03-40-51.489938/phantom_Y4w_mX.log to /var/loadtest/logs/2021-07-26_03-40-51.489938/phantom_Y4w_mX.log
2021-07-26 03:40:57,748 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-26_03-40-51.489938/phantom_Y4w_mX.log
